// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: idl/services.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BetOnBetService_CompletedScores_FullMethodName = "/services.BetOnBetService/CompletedScores"
)

// BetOnBetServiceClient is the client API for BetOnBetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BetOnBetServiceClient interface {
	CompletedScores(ctx context.Context, in *CompletedScoresRequest, opts ...grpc.CallOption) (*CompletedScoresResponse, error)
}

type betOnBetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBetOnBetServiceClient(cc grpc.ClientConnInterface) BetOnBetServiceClient {
	return &betOnBetServiceClient{cc}
}

func (c *betOnBetServiceClient) CompletedScores(ctx context.Context, in *CompletedScoresRequest, opts ...grpc.CallOption) (*CompletedScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletedScoresResponse)
	err := c.cc.Invoke(ctx, BetOnBetService_CompletedScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BetOnBetServiceServer is the server API for BetOnBetService service.
// All implementations must embed UnimplementedBetOnBetServiceServer
// for forward compatibility.
type BetOnBetServiceServer interface {
	CompletedScores(context.Context, *CompletedScoresRequest) (*CompletedScoresResponse, error)
	mustEmbedUnimplementedBetOnBetServiceServer()
}

// UnimplementedBetOnBetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBetOnBetServiceServer struct{}

func (UnimplementedBetOnBetServiceServer) CompletedScores(context.Context, *CompletedScoresRequest) (*CompletedScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompletedScores not implemented")
}
func (UnimplementedBetOnBetServiceServer) mustEmbedUnimplementedBetOnBetServiceServer() {}
func (UnimplementedBetOnBetServiceServer) testEmbeddedByValue()                         {}

// UnsafeBetOnBetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BetOnBetServiceServer will
// result in compilation errors.
type UnsafeBetOnBetServiceServer interface {
	mustEmbedUnimplementedBetOnBetServiceServer()
}

func RegisterBetOnBetServiceServer(s grpc.ServiceRegistrar, srv BetOnBetServiceServer) {
	// If the following call pancis, it indicates UnimplementedBetOnBetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BetOnBetService_ServiceDesc, srv)
}

func _BetOnBetService_CompletedScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletedScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BetOnBetServiceServer).CompletedScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BetOnBetService_CompletedScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BetOnBetServiceServer).CompletedScores(ctx, req.(*CompletedScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BetOnBetService_ServiceDesc is the grpc.ServiceDesc for BetOnBetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BetOnBetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.BetOnBetService",
	HandlerType: (*BetOnBetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompletedScores",
			Handler:    _BetOnBetService_CompletedScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idl/services.proto",
}
