// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: idl/services.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletedScoresRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	League string `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	Date   string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *CompletedScoresRequest) Reset() {
	*x = CompletedScoresRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletedScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedScoresRequest) ProtoMessage() {}

func (x *CompletedScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedScoresRequest.ProtoReflect.Descriptor instead.
func (*CompletedScoresRequest) Descriptor() ([]byte, []int) {
	return file_idl_services_proto_rawDescGZIP(), []int{0}
}

func (x *CompletedScoresRequest) GetLeague() string {
	if x != nil {
		return x.League
	}
	return ""
}

func (x *CompletedScoresRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type BoxScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team    string `protobuf:"bytes,1,opt,name=Team,proto3" json:"Team,omitempty"`
	Op      string `protobuf:"bytes,2,opt,name=Op,proto3" json:"Op,omitempty"`
	Score   string `protobuf:"bytes,3,opt,name=Score,proto3" json:"Score,omitempty"`
	OpScore string `protobuf:"bytes,4,opt,name=OpScore,proto3" json:"OpScore,omitempty"`
	Winner  string `protobuf:"bytes,5,opt,name=Winner,proto3" json:"Winner,omitempty"`
}

func (x *BoxScore) Reset() {
	*x = BoxScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoxScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxScore) ProtoMessage() {}

func (x *BoxScore) ProtoReflect() protoreflect.Message {
	mi := &file_idl_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxScore.ProtoReflect.Descriptor instead.
func (*BoxScore) Descriptor() ([]byte, []int) {
	return file_idl_services_proto_rawDescGZIP(), []int{1}
}

func (x *BoxScore) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *BoxScore) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *BoxScore) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *BoxScore) GetOpScore() string {
	if x != nil {
		return x.OpScore
	}
	return ""
}

func (x *BoxScore) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

type CompletedScoresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxScore []*BoxScore `protobuf:"bytes,1,rep,name=boxScore,proto3" json:"boxScore,omitempty"`
}

func (x *CompletedScoresResponse) Reset() {
	*x = CompletedScoresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompletedScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedScoresResponse) ProtoMessage() {}

func (x *CompletedScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedScoresResponse.ProtoReflect.Descriptor instead.
func (*CompletedScoresResponse) Descriptor() ([]byte, []int) {
	return file_idl_services_proto_rawDescGZIP(), []int{2}
}

func (x *CompletedScoresResponse) GetBoxScore() []*BoxScore {
	if x != nil {
		return x.BoxScore
	}
	return nil
}

var File_idl_services_proto protoreflect.FileDescriptor

var file_idl_services_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x64, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x44,
	0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x67,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x22, 0x76, 0x0a, 0x08, 0x42, 0x6f, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x4f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x70, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x17,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x62, 0x6f, 0x78, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x08, 0x62,
	0x6f, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x69, 0x0a, 0x0f, 0x42, 0x65, 0x74, 0x4f, 0x6e,
	0x42, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x56, 0x0a, 0x0f, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x20, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_services_proto_rawDescOnce sync.Once
	file_idl_services_proto_rawDescData = file_idl_services_proto_rawDesc
)

func file_idl_services_proto_rawDescGZIP() []byte {
	file_idl_services_proto_rawDescOnce.Do(func() {
		file_idl_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_services_proto_rawDescData)
	})
	return file_idl_services_proto_rawDescData
}

var file_idl_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idl_services_proto_goTypes = []any{
	(*CompletedScoresRequest)(nil),  // 0: services.CompletedScoresRequest
	(*BoxScore)(nil),                // 1: services.BoxScore
	(*CompletedScoresResponse)(nil), // 2: services.CompletedScoresResponse
}
var file_idl_services_proto_depIdxs = []int32{
	1, // 0: services.CompletedScoresResponse.boxScore:type_name -> services.BoxScore
	0, // 1: services.BetOnBetService.CompletedScores:input_type -> services.CompletedScoresRequest
	2, // 2: services.BetOnBetService.CompletedScores:output_type -> services.CompletedScoresResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_services_proto_init() }
func file_idl_services_proto_init() {
	if File_idl_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_services_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CompletedScoresRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_services_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BoxScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_services_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CompletedScoresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_services_proto_goTypes,
		DependencyIndexes: file_idl_services_proto_depIdxs,
		MessageInfos:      file_idl_services_proto_msgTypes,
	}.Build()
	File_idl_services_proto = out.File
	file_idl_services_proto_rawDesc = nil
	file_idl_services_proto_goTypes = nil
	file_idl_services_proto_depIdxs = nil
}
